gooddata/zuul

requirements.txt
This is a workaround for bug
https://github.com/sigmavirus24/github3.py/issues/634
Which is in fact between github3.py and uritemplate.py (which was
recently deprecated in favour of uritemplate). As a quick fix, adding
and locking this dependency to zuul as we currently don't have control
over the github3.py.
Revert once the bug in github3.py is fixed.
Change-Id: Ifdd88df7379caa400c9605026da8903ddcb6cd62
=> Install and lock uritemplate.py

zuul/connection/gerrit.py, zuul/connection/github.py, zuul/connection/smtp.py, zuul/layoutvalidator.py, zuul/reporter/gerrit.py, zuul/trigger/gerrit.py, zuul/trigger/zuultrigger.py
Not sure if schema requirements changed but it is no longer valid to
use:
Schema({}, extra=True)
The docs say that should be avoided and instead you should use:
Schema(dict)
To indicate a dict that can have any key: value pairs. Additionally
extra=True appears to be replaced with extra=ALLOW_EXTRA so update that
in cases where we have some subset of desired keys.
Change-Id: Ia9f4d535b9b633e703465f155c4722d9a58c45a7
(cherry picked from commit 0a38b6c5680f5c7cb23fab91dbfc84f88024829d)
=> Handle dict extras in Voluptuous Schema

tests/test_cloner.py, zuul/lib/cloner.py
Used str.replace instead of re.sub since regexes are not needed
=> BUGFIX: SETI-379 zuul-cloner tries to fetch a wrong revision

Makefile, zuul.spec
Got rid of installing dependencies from cache and adapted zuul.spec and Makefile so it's possible to build zuul on jenkins (either through gooddata/gdc-generic-bundle or directly from zuul repository by rpmbuild-el6-tools job).
=> SETI-772: Build zuul from gdc-generic-bundle

integration/spec/gerrit_workflow_spec.rb, integration/spec/github_workflow_spec.rb
Raise the timeout for the gate to be the same as for the check, which is
5 minutes.
30 seconds was really too few.
=> SETI-866: Raise timeouts for integration tests

tox.ini
Recently, unit tests for zuul started to fail on CI because of
timeouts. This should solve it.
=> TRIVIAL: Raise timeouts for individual tests

zuul.spec
Right now we build zuul on two different places: 1. as a part of testing pipeline through gooddata/zuul/zuul.spec, 2. production version through gdc-generic-bundle/packages/zuul/files/zuul.spec. Let's get rid of the spec file in gdc-generic-bundle, so the building is unified and less prone to error.
=> SETI-376: Move and edit zuul.spec to build via rpmbuild-el7-tools

tests/base.py, tests/test_github.py, zuul/model.py
Zuul only checks changes by PR number when deleting the old ones.
Check project name too in isUpdateOf()
=>  SETI-1210: Zuul can mix PRs from different projects

zuul/connection/github.py
It works like this:
```
> gh = github3.login('mytoken')
> repo = gh.repository('gooddata', 'ci-infra')
> [f['filename'] for f in repo.compare_commits('c403edb', '4d73941').files]
[u'.jenkins-jobs.ini.tpl', u'jenkins/jobs/templates/util-jobs.yaml']
```
=> SETI-1023: extract filenames after push event correctly

tests/test_model.py, zuul/model.py
Let's check for existence of attributes in the other object first
to avoid exceptions in equals(self, other) function.
Also check for project attribute in Change.equals (bugfix).
=> SETI-1306: Correct Change, NullChange, Ref equals() functions

tests/fixtures/layout-abort-pipelines.yaml, tests/test_github.py, tests/test_scheduler.py, zuul/model.py, zuul/scheduler.py
Test that abort-pipeline does not abort same change number but
from different project.
=> SETI-401: Test some corner cases of abort-pipeline feature

integration/spec/git_repo.rb, integration/spec/github_workflow_spec.rb
Delete created test branch at the end of every integration test,
so the big number of test branches do not slow down the test jobs.
=> SETI-1461: integration tests - remove temporary branches on github

tests/test_github.py, zuul/connection/github.py, zuul/exceptions.py, zuul/merger/client.py, zuul/merger/merger.py, zuul/merger/server.py, zuul/model.py, zuul/scheduler.py, zuul/source/github.py
git ref pull/X/head is sometimes wrong (error of Github).
Catch these errors by checking that SHA of commit fetched by merger
equals SHA of PR head acquired from Github webhook event JSON.
=> SETI-1706: Check that SHA of PR head fetched by merger is correct

tests/base.py, tests/test_github.py, zuul/reporter/github.py
As part of SETI-377, order of reporting items to github PR was changed
to report failure more easily in case of merge failure.
Particularly, reported was supposed to merge the PR and then change
the pipeline status. This does not work on protected branches:
required status needs to be reported first and then merging is allowed
by Github.
Let's change the order of reporting, so that reporter reports status and
labels first and then merge the PR. Comment reporting happens after
merging PR to prevent reporting 2 comments (first "Merge successful",
second "Merge failed") which would be confusing.
=> BUGFIX: SETI-1767 github reporter: report status and labels before merge

requirements.txt
gear package was recently updated to 0.12.0 and does not work
with zuul anymore. Lock the version to 0.11.1, which works fine.
=> TRIVIAL: Lock gear dependency to 0.11.1

tests/fixtures/layout-github.yaml, tests/test_github.py
One has to test on repository which is created in tests/base.py. Repo
post-file-project was not there, so it resulted in this exception being
logged in testr output:
stderr: 'fatal: repository '/tmp/tmpwGKy8Z/zuul-test/upstream/org/post-file-project' does not exist
It was not fatal for the test, however it's confusing when searching for
=> avoid exception in github post file-filter test

zuul/cmd/server.py, zuul/scheduler.py
They were introduced by
0845c53daa87d602af7e96d4cb003bee2bcc17b0
2c9343aa225264f97ca3c1c0273f0daca2eb089e
No idea how did they passed the tests and the Jenkins builds do not
exist anymore for investigating.
=> fix pep8 violations

tests/base.py, tox.ini
Our testing infrastructure is sometimes too slow to run more
complex tests in time.
Increase timeout in function waitUntilSettled from 10 to 20 sec.
Increase overall timeout for every test from 60 to 150 sec.
=> TRIVIAL: Increase timeouts in testing environment

requirements.txt
Before this commit, an alpha version fo github3.py library was
used because some new features yet under development were used.
The situation has changed and github3.py has released a few stable
versions since then. Let's bump the library version so we do not
use an unstable version.
Release notes were checked and there are no changes needed in
zuul/connection/github.py (the only place github3.py is used).
=> TRIVIAL: Bump github3.py version from 1.0.0a2 to 1.3.0

tests/test_scheduler.py, tests/test_zuultrigger.py, zuul/scheduler.py
merge_failure message is reported to github PR in case zuul-merger
fails to merge the change into base branch. This usually happens
in case of merge conflicts. Otherwise, it is usually an error in
zuul-merger.
Update the merge_failure message so it accurately describes the
situation.
=> SETI-1707: Update default merge_failure message

tests/test_github.py, zuul/reporter/github.py
Github reporter displays URL to zuul status page with filter for
the current PR's build. The filter string format was broken. This
commit fixes the format.
=> SETI-2852: Fix zuul status page URLs in github status checks

zuul.spec
There are two new files installed, but not packaged to rpm. Let's add it
into specfile.
Fix for rpmbuild error
error: Installed (but unpackaged) file(s) found:
/opt/gdc/zuul/share/doc/jwcrypto/LICENSE
/opt/gdc/zuul/share/doc/jwcrypto/README.md
=> BUGFIX: Add missing installed files to specfile

tools/zuul-clear-refs.py
Reverts gooddata/zuul#89
if we go this way we also need to update crontab in zuul to check exit code otherwise it will ignore also case script exited with failure. So this solution will be more better : https://github.com/gooddata/puppet/pull/34801/files
=> Revert "CONFIG: SETI-3262 Change logging stream from stderr to stdout for script zuul-clear-refs"

requirements.txt
The version 2.1.9 of GitPython is not available in PIP anymore. But we can safely use newer versions as tested here: https://checklist.intgdc.com/job/ci-infra/job/ci-infra-compare-jobs/4658/console
I have checked that these version are not used on zuul main server (the GitPython package there is installed from RPMs).
=> SETI-3922: Upgrade requirements for GitPython

requirements.txt
As newer version require higher python version and may
break other integration
Proper solution will be done in SETI-3827
=> SETI-5534: Lock Github3.py version to 1.3.0

zuul.spec, zuul/connection/github.py
Where it can be applied for all events instead of only the PR creating event
=> SETI-5687 Move the sleep after hooking to __dispatch_event()
